version: "3.8"

networks:
  nginx:
    driver: overlay
    name: nginx
  mysql:
    driver: overlay
    name: mysql

services:
  nginx:
    image: nginx:1.22.0-alpine
    networks:
      - nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/ssl/:/etc/nginx/ssl/
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/conf.d/:/etc/nginx/conf.d/
      - /etc/nginx/html/:/etc/nginx/html/
    logging:
      options:
        max-size: 10m
        max-file: 3
  
  mysql:
    image: mysql:8.0.29
    networks:
      - nginx
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: ioseek.cn
    volumes:
      - /var/lib/mysql/:/var/lib/mysql/
    logging:
      options:
        max-size: 10m
        max-file: 3
  
  redis:
    image: redis:7.0.0-alpine
    networks: 
      - nginx
    command:
      - "--requirepass"
      - "ioseek.cn"
    logging:
      options: 
        max-size: 10m
        max-file: 3
    
  prometheus:
    image: prom/prometheus:v2.35.0
    networks:
      - nginx
    volumes:
      - /etc/ioseek/prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/lib/prometheus/:/prometheus/
    command:
      - "--storage.tsdb.retention.time=7d"
    logging:
      options:
        max-size: 10m
        max-file: 3
  
  alertmanager:
    image: prom/alertmanager:v0.24.0
    networks:
      - nginx
    volumes:
      - /etc/ioseek/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - /var/lib/alertmanager/:/alertmanager/
    logging:
      options:
        max-size: 10m
        max-file: 3
  
  blackbox_exporter:
    image: prom/blackbox-exporter:v0.20.0
    networks:
      - nginx
    volumes:
      - /etc/ioseek/blackbox.yml:/etc/blackbox_exporter/config.yml
    logging:
      options:
        max-size: 10m
        max-file: 3

  ioseek:
    image: jeyrce/ioseek:latest
    networks:
      - nginx
      - mysql
    depends_on:
      - mysql
      - redis
    volumes:
      - /etc/ioseek/media/:/etc/ioseek/media/
    logging:
      options:
        max-size: 10m
        max-file: 3
  
  ishare:
    image: jeyrce/ishare:v1.0.1
    networks:
      - nginx
    volumes:
      - /root/db.sqlite3:/ishare/db.sqlite3
      - /root/media/:/ishare/media/
    logging:
      options:
        max-size: 10m
        max-file: 3
